# Generated by Django 5.1.5 on 2025-02-17 05:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, unique=True)),
                ('price', models.PositiveIntegerField(help_text='Coins required to play this difficulty level.')),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
            },
        ),
        migrations.CreateModel(
            name='CoinReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewards', models.JSONField(default=list, help_text='A list of coin rewards for each question (e.g., [10, 20, 30, ...]).')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.difficultylevel')),
            ],
            options={
                'verbose_name': 'Coin Reward',
                'verbose_name_plural': 'Coin Rewards',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trivia_game.category')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trivia_game.difficultylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text.')),
                ('correct_answer', models.CharField(help_text='The correct answer to the question.', max_length=255)),
                ('wrong_answer1', models.CharField(help_text='First wrong answer.', max_length=255)),
                ('wrong_answer2', models.CharField(help_text='Second wrong answer.', max_length=255)),
                ('wrong_answer3', models.CharField(help_text='Third wrong answer.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trivia_game.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.difficultylevel')),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.gamesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_game.question')),
            ],
            options={
                'unique_together': {('game_session', 'question')},
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='questions',
            field=models.ManyToManyField(through='trivia_game.GameSessionQuestion', to='trivia_game.question'),
        ),
    ]
