"""
Django settings for eduPath project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ASGI_APPLICATION = 'eduPath.asgi.application'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-exyrenh^i(18fgnoh!5n(0=720$mrr#@di7_4x24ao00x#+6wj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'eduPathCare.User'

PAYSTACK_SECRET_KEY = 'sk_test_93f0e40b7afbe400567ccb16aaa9b0fde7433885'
PAYSTACK_PUBLIC_KEY = 'pk_test_654348935a46c81772e0417720957bca88bdce53'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "eduPathCare",
    'django_summernote',
    'widget_tweaks',
    'tailwind',
    'theme',
    'django_browser_reload',
    #'django_sonar',
    'trivia_game',
    #'study_planner',
    'rest_framework',
    'polls',
]

TAILWIND_APP_NAME = 'theme'

TAILWIND_CSS_PATH = 'css/dist/styles.css'

INTERNAL_IPS = [
    "127.0.0.1",
]

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"



#SUMMERNOTE_THEME = 'bs5'  # Show summernote with Bootstrap4

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    #'django_sonar.middlewares.requests.RequestsMiddleware',
]

ROOT_URLCONF = 'eduPath.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'eduPath.wsgi.application'


# settings.py
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Set the timezone to your local timezone
#TIME_ZONE = 'Africa/Lagos'  # Replace with your timezone, e.g., 'America/New_York', 'Europe/London', etc.


# import tzlocal

# # Automatically detect the system's time zone
# SYSTEM_TIME_ZONE = tzlocal.get_localzone()

# # Set Django's TIME_ZONE to the system's time zone
# TIME_ZONE = SYSTEM_TIME_ZONE




USE_I18N = True




USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'eduPathCare/static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SUMMERNOTE_CONFIG = {

    # You can put custom Summernote settings
    'summernote': {

        # Change editor size
        'width': '100%',
        'height': '480',
        
    },
       
}


# DJANGO_SONAR = {
#     'excludes': [
#         STATIC_URL,
#         MEDIA_URL,
#         '/sonar/',
#         '/admin/',
#         '/__reload__/',
#     ],
# }