# Generated by Django 5.1.5 on 2025-03-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPathCare', '0002_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_year',
        ),
    ]
