# Generated by Django 5.1.5 on 2025-03-07 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPathCare', '0003_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('subject_selected', 'Subject Selected'), ('quiz_attempted', 'Quiz Attempted'), ('final_exam_attempted', 'Final Exam Attempted'), ('flashcard_viewed', 'Flashcard Viewed'), ('coin_purchased', 'Coin Purchased'), ('coin_withdrawn', 'Coin Withdrawn'), ('profile_updated', 'Profile Updated'), ('password_reset', 'Password Reset')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
