# Generated by Django 5.1.7 on 2025-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPathCare', '0004_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
